Feature: Cluster content library — admin provisions content, all users consume it
  As a platform administrator
  I want to provision the full 14-day course content once per job cluster
  (generated by the LLM under my control, or uploaded/edited by me)
  So that every learner joining that cluster consumes the admin-provisioned
  content instantly, with zero per-user LLM calls — individual users were
  failing with "generation failed" because the free-tier LLM chain could not
  absorb ~31 LLM calls on every enrollment (architecture.md §2 principle 3:
  "Cohort amortization — generate one sprint plan per cluster; users share
  content, each keeps their own day counter").

  Background:
    Given the app is running against the live test database

  # ── Admin provisioning surface ──────────────────────────────────────
  Scenario: Admin sees the content library status for a cluster
    Given I am logged in as an admin user
    When I GET "/admin/content/email-automation"
    Then the response status is 200
    And the page contains the text "Content Library"

  Scenario: Admin generates the library for a cluster from the live job feed
    Given I am logged in as an admin user
    When the content library worker runs for cluster "email-automation"
    Then the library for cluster "email-automation" has a lesson for every day 1-14
    And the library for cluster "email-automation" has anatomy for all 3 projects

  Scenario: Learner enrollment consumes the library — zero per-user LLM calls
    Given the content library worker has run for cluster "email-automation"
    And a logged-in user
    When I POST to "/sprints/email-automation/start"
    Then the response redirects to a sprint dashboard
    And day 1 of the new sprint shows the library lesson with no per-user LLM call

  Scenario: A second learner on the same cluster consumes the SAME content
    Given the content library worker has run for cluster "email-automation"
    And the library lesson for day 4 has already been consumed by a learner
    When another logged-in user starts a sprint for cluster "email-automation"
    Then both sprints render the same day-4 lesson content
    And the LLM was called zero times for either learner

  Scenario: Library lessons keep the engagement fields (hook, overview, pre-quiz)
    Given the content library worker has run for cluster "email-automation"
    And a logged-in user with an active sprint "s1" for cluster "email-automation"
    When I GET "/sprints/s1/day/1"
    Then the response status is 200
    And the page contains the text "Today you'll learn"
    And the page contains an element with attribute "data-lesson-player"

  Scenario: Copy-work rubric from the library is submittable (Gate A still works)
    Given the content library worker has run for cluster "email-automation"
    And a logged-in user with an active sprint "s1" for cluster "email-automation"
    When I GET "/sprints/s1/day/4"
    Then the response status is 200
    And the page contains the text "Copy-Work"
    And the page contains the text "rubric verified at Gate A"

  Scenario: Admin can edit one library day (override the generated content)
    Given I am logged in as an admin user
    And the content library worker has run for cluster "email-automation"
    When I POST to "/admin/content/email-automation/day/7" with form data {"title": "Pricing your first contract", "script": "Admin-written script."}
    Then the library for cluster "email-automation" has day 7 titled "Pricing your first contract"
    And a new learner's day 7 shows the admin-edited title

  Scenario: Admin can regenerate the library from scratch
    Given I am logged in as an admin user
    And the content library worker has run for cluster "email-automation"
    When I POST to "/admin/content/email-automation/generate"
    Then the response status is 200
    And the JSON has field "status" equal to "generating"
    And the library for cluster "email-automation" has a lesson for every day 1-14

  Scenario: Non-admin cannot provision content
    Given a logged-in user
    When I POST to "/admin/content/email-automation/generate"
    Then the response status is 403

  # ── Fallback behaviour (no library yet) ─────────────────────────────
  Scenario: Without a library, a new sprint falls back to per-sprint generation
    Given no content library exists for cluster "web-scraping"
    And a logged-in user
    When I POST to "/sprints/web-scraping/start"
    Then the response redirects to a sprint dashboard
    And the sprint's generation status eventually reports lessons for every day
    And the per-user LLM fallback was used exactly once for this sprint

  # ── Housekeeping ────────────────────────────────────────────────────
  Scenario: Purging a learner's sprint never deletes the shared library
    Given the content library worker has run for cluster "email-automation"
    And a logged-in user with an active sprint "s1" for cluster "email-automation"
    When the sprint "s1" is deleted
    Then the library for cluster "email-automation" still has a lesson for every day 1-14
