"""
PanelContent.js Writer — Generates the PanelContent.js file for Remotion
"""
import json
import os


def write_panel_content(panels: list, output_dir: str) -> str:
    """
    Write PanelContent.js from panel data.
    Returns the path to the written file.
    """
    panels_js = _render_panels_js(panels)
    
    # Calculate timing
    total_words = sum(len(p["words"].split()) for p in panels)
    # Estimate video seconds (~150 words per minute = ~2.5 words/sec)
    estimated_seconds = max(60, total_words / 2.5)
    
    js_content = f"""// Auto-generated by FreelanceLaunch video pipeline
const FPS = 30;

const PANELS = {panels_js};

const WORD_COUNTS = PANELS.map(p => p.words.split(" ").length);
const TOTAL_WORDS = WORD_COUNTS.reduce((a, b) => a + b, 0);
const VIDEO_SECONDS = {estimated_seconds:.2f};
const TOTAL_FRAMES_AUDIO = Math.round(VIDEO_SECONDS * FPS);
const GAP_FRAMES = (PANELS.length - 1) * 10;
const CONTENT_FRAMES = TOTAL_FRAMES_AUDIO - GAP_FRAMES;
const RAW_DURATIONS = WORD_COUNTS.map(w => Math.max(30, Math.round(w / TOTAL_WORDS * CONTENT_FRAMES)));
const RAW_SUM = RAW_DURATIONS.reduce((a, b) => a + b, 0);
RAW_DURATIONS[RAW_DURATIONS.length - 1] += TOTAL_FRAMES_AUDIO - RAW_SUM - GAP_FRAMES;
const DURATIONS = RAW_DURATIONS;
const TOTAL_FRAMES = DURATIONS.reduce((a, b) => a + b, 0) + GAP_FRAMES;

const PHASE_STARTS = [];
let accum = 0;
for (let i = 0; i < DURATIONS.length; i++) {{
  PHASE_STARTS.push(accum);
  accum += DURATIONS[i] + 10;
}}

const KEYWORDS = new Set([
  "skill", "learn", "build", "create", "freelance", "client",
  "project", "workflow", "automate", "develop", "design",
  "system", "process", "tool", "value", "result", "market",
]);

export {{ PANELS, DURATIONS, TOTAL_FRAMES, PHASE_STARTS, VIDEO_SECONDS, KEYWORDS }};
"""
    
    filepath = os.path.join(output_dir, "src", "PanelContent.js")
    os.makedirs(os.path.dirname(filepath), exist_ok=True)
    
    with open(filepath, "w") as f:
        f.write(js_content)
    
    return filepath


def write_keywords(keywords: list, two_panel_path: str):
    """Update KEYWORDS in TwoPanelStack.jsx."""
    if not keywords:
        return
    
    js_path = os.path.join(two_panel_path, "src", "TwoPanelStack.jsx")
    if not os.path.exists(js_path):
        return
    
    with open(js_path, "r") as f:
        content = f.read()
    
    # Find and replace KEYWORDS set
    keyword_str = ", ".join(f'"{k}"' for k in keywords[:20])
    new_set = f"const KEYWORDS = new Set([{keyword_str}])"
    
    import re
    content = re.sub(
        r'const KEYWORDS = new Set\(\[.*?\]\)',
        new_set,
        content,
        flags=re.DOTALL
    )
    
    with open(js_path, "w") as f:
        f.write(content)


def _render_panels_js(panels: list) -> str:
    """Render panels as JavaScript array string."""
    panel_strs = []
    for p in panels:
        graph = p.get("graph", {})
        graph_str = json.dumps(graph) if graph else "null"
        
        panel_str = f"""{{
  id: "{p['id']}",
  title: "{p['title']}",
  caption: "{p['caption']}",
  color: "{p['color']}",
  accent: "{p['accent']}",
  diagramType: "{p['diagramType']}",
  imgLabel: "{p.get('imgLabel', '')}",
  words: `{p['words']}`,
  graph: {graph_str},
}}"""
        panel_strs.append(panel_str)
    
    return "[\n" + ",\n".join(panel_strs) + "\n]"
